/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2023-03-31 01:50:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import ucl.ac.uk.main.Model;
import ucl.ac.uk.main.Model;
import ucl.ac.uk.main.*;

public final class viewAllLists_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("ucl.ac.uk.main");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ucl.ac.uk.main.Model");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>View Lists</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"viewAllLists.css\"/>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h1>Lists</h1>\n");
      out.write("<ul>\n");
      out.write("  <a href=\"/insert\" ><button style=\"margin-bottom: 15px;margin-top: 10px\">Add Lists</button></a><br/>\n");
      out.write("  <a href=\"/search\" ><button style=\"margin-bottom: 15px;\">Search</button></a>\n");

  ArrayList<ItemList> itemLists = (ArrayList<ItemList>) request.getAttribute("itemLists");


  for(ItemList itemList : itemLists)
  {
    out.print("<li>");
    out.print("<div class=\"card\">");
    out.print("<div class=\"card-header\" style=\"font-size: 30px;\">" + itemList.getName() + "<a href=\"/rename?id=" + itemList.getId() + "&name=" + itemList.getName() + "\" ><div class=\"card-edit-icon\" style=\"font-size: 20px;\">&#9998;</div></a></div>");
    out.print("<br/>");
    out.print("<div class=\"card-body-container\">");
    if (!itemList.getText().equals("")) {
      out.print("<div class=\"card-body-text\" style=\"font-size: 20px;\">Text : " + itemList.getText() + "</a></div><br/>");
      out.print("<br/>");
    }
    if (!itemList.getUrl().equals("")) {
      out.print("<div class=\"card-body-url\" style=\"font-size: 20px;\">URL : " + "<a href=" + itemList.getUrl() + ">" + "Click here to view url" + "</a>" + "</a></div><br/>");
      out.print("<br/>");
    }
    if (itemList.getLinkedlist()!=null && !itemList.getLinkedlist().equals("") && !itemList.getLinkedlist().equals("null")){
      out.print("<div class=\"card-body-url\" style=\"font-size: 20px;\">LinkedList : <a href=\"/view?id=" + itemList.getLinkedlist() + "\" style=\"display: inline-block\">Linked List</a></div><br/>");
    };
    out.print("<div class=\"card-image-container\">");
    if (!itemList.getImage().equals("images/default-image.png")) {
      out.print("<img src=\"" + itemList.getImage() + "\" width=\"200\" height=\"150\" style=\"padding-bottom: 10px;\"></div>");
      out.print("</div>");
    }
    out.print("<a href=\"/delete?id=" + itemList.getId() + "\" style=\"padding-right: 10px;\"><button type=\"submit\">Delete List</button></a>");
    out.print("<a href=\"/edit?id=" + itemList.getId() + "\" style=\"padding-right: 10px;\"><button type=\"submit\">Edit Items</button></a>");
    out.print("<a href=\"/view?id=" + itemList.getId() + "\" style=\"padding-right: 10px;\"><button type=\"submit\">View List</button></a>");
    out.print("</li>");

  }


      out.write("\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
